"""new1

Revision ID: 72b0be59bbc3
Revises: 4c9c89601550
Create Date: 2025-03-03 19:36:58.355349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72b0be59bbc3'
down_revision = '4c9c89601550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.alter_column('expiry_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.alter_column('expiry_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
