"""Create missing table duration in Medicine model

Revision ID: b20794b64c39
Revises: 
Create Date: 2025-02-23 13:10:39.237566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b20794b64c39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
